#!/usr/bin/bash
. ./.importdir
./clean -r "/var/www/local.missionpossiblekids.org/htdocs/sites/all/modules/civicrm" \
	-f "$IMPORTDIR/agent_dump_test.csv" \
	--action "createContact" \
	-t "Individual" \
	-s "Agent" \
	--rel-type-id 11 \
	--rel-ext-id-col chapter_ext_id
